export interface OromoPillar {
  id: string;
  category: 'governance' | 'celebration' | 'music' | 'cuisine' | 'attire' | 'philosophy';
  titleEn: string;
  titleAm: string;
  titleOm: string;
  subtitleEn: string;
  subtitleAm: string;
  subtitleOm: string;
  descEn: string;
  descAm: string;
  descOm: string;
  image: string;
  iconName: string;
  tagEn: string;
  tagAm: string;
  tagOm: string;
  highlightsEn: string[];
  highlightsAm: string[];
  highlightsOm: string[];
  quoteEn?: string;
  quoteAm?: string;
  quoteOm?: string;
}

export interface OromiaGalleryPhoto {
  id: string;
  titleEn: string;
  titleAm: string;
  titleOm: string;
  captionEn: string;
  captionAm: string;
  captionOm: string;
  category: 'all' | 'irreecha' | 'nature' | 'heritage' | 'attire' | 'culinary';
  locationEn: string;
  locationAm: string;
  locationOm: string;
  image: string;
  aspectRatio: 'tall' | 'wide' | 'square';
}

export const OROMO_CULTURE_PILLARS: OromoPillar[] = [
  {
    id: 'gadaa',
    category: 'governance',
    iconName: 'Landmark',
    titleEn: 'The Gadaa System: Democratic Heritage',
    titleAm: 'የገዳ ሥርዓት፡ ጥንታዊ የዴሞክራሲ ቅርስ',
    titleOm: 'Sirna Gadaa: Dhaala Dimokraasii Addunyaa',
    subtitleEn: 'UNESCO Intangible Cultural Heritage of Humanity',
    subtitleAm: 'በዩኔስኮ የተመዘገበ የማይዳሰስ የሰው ልጅ ቅርስ',
    subtitleOm: 'Dhaala Aadaa Qabatamaa Hin Taane Kan UNESCO',
    descEn: 'The Gadaa system is an indigenous, egalitarian democratic socio-political governance system developed by the Oromo people over centuries. Structured into five rotating generations with eight-year terms, it guides politics, judicial arbitration, defense, and social harmony without hereditary rule.',
    descAm: 'የገዳ ሥርዓት በኦሮሞ ሕዝብ የተመሠረተና የተዘረጋ ጥንታዊና ሁሉን አቀፍ የዴሞክራሲ መዋቅር ነው። ሥልጣን በየስምንት ዓመቱ በሰላማዊ መንገድ ከትውልድ ወደ ትውልድ በኦዳ ዛፍ ጥላ ሥር በሚካሄድ የባሊ ርክክብ ይተላለፋል።',
    descOm: 'Sirni Gadaa sirna dimokraasii, siyaasaa, diinagdee fi hawaasummaa Oromooti. Waggaa saddeet saddeetiin baallii wal-harkaa fuudhuudhaan nagaan aangoon kan itti jijjiiramu dhaala guddaadha.',
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?q=80&w=1200&auto=format&fit=crop',
    tagEn: 'Governance & Democracy',
    tagAm: 'ዴሞክራሲና አስተዳደር',
    tagOm: 'Bulchiinsa & Dimokraasii',
    highlightsEn: [
      'Peaceful, mandatory transfer of power every eight years (Baallii Wal-harkaa Fuudhuu)',
      'Legislative councils held at the sacred Chaffe under the shade of the grand Odaa tree',
      'Lifelong education through 5 progressive age-grades (Dabballee, Foollee, Qondaala, Raaba Doorii, Gadaa)',
      'Supreme arbitration by the Abbaa Gadaa upholding truth (Dhugaa) and cosmic balance (Safuu)',
    ],
    highlightsAm: [
      'በየስምንት ዓመቱ የሚከናወን ሰላማዊና አስገዳጅ የሥልጣን ርክክብ (የባሊ ርክክብ)',
      'በኦዳ ዛፍ ጥላ ሥር በጨፌ ጉባኤ የሚካሄድ የሕግ አወጣጥና ዳኝነት',
      'በአምስት የዕድሜ እርከኖች የሚካሄድ የሕይወትና የመሪነት ትምህርት',
      'እውነትን (ዱጋ) እና የሕዝብ ሰላምን የሚያስጠብቅ የአባ ገዳ አመራር',
    ],
    highlightsOm: [
      'Waggaa saddeet saddeetiin baallii wal-harkaa fuudhuudhaan aangoof nagaan jijjiirraan godhama',
      'Kora Chaffee kan Odaa jalatti gaggeeffamuun seerri tumama',
      'Sadarkaalee gurguddoo shaniin (Dabballee, Foollee, Qondaala, Raaba Doorii, Gadaa) leenjiin kennama',
      'Dhugaa fi Safuu eeguun abbaa Gadaatiin bulchiinsi haqaa mirkanaa\'a',
    ],
    quoteEn: '“Under the sacred Odaa, laws are made with consensus, and power belongs to the collective will of the people.”',
    quoteAm: '“በተቀደሰው የኦዳ ጥላ ሥር ሕጎች በሕዝብ ይወጣሉ፤ ሥልጣንም የሕዝብ ነው!”',
    quoteOm: '“Odaa jalatti seerri tumama; dhugaan ifa baha; nagaan dagaaga.”',
  },
  {
    id: 'irreecha',
    category: 'celebration',
    iconName: 'Sparkles',
    titleEn: 'Irreecha Birraa: The Sacred Thanksgiving',
    titleAm: 'የኢሬቻ በዓል፡ የክረምት መውጫ የምስጋና በዓል',
    titleOm: 'Ayyaana Irreechaa: Irreecha Birraa fi Galata Waaqaa',
    subtitleEn: 'Thanksgiving for Life, Water, Light & Renewal',
    subtitleAm: 'ለፈጣሪ የሚቀርብ የፍቅር፣ የሰላምና የውበት ምስጋና',
    subtitleOm: 'Galata Waaqaa, Ifa Birraa fi Nagaa Ummataa',
    descEn: 'Irreecha is the premier Thanksgiving festival of the Oromo people, held annually at the end of the rainy season (Birraa) as Meskerem unfolds. Millions gather at sacred waters—most notably Hora Harsadi in Bishoftu and Hora Finfinnee—holding freshly plucked green grass (Coqorsa) and golden Adey Abeba blooms to praise Waaqa (God) for health, harvest, and peace.',
    descAm: 'ኢሬቻ የክረምቱ ጨለማና ዝናብ አልፎ ብሩህ የብርሃን ወር ሲመጣ የሚከበር ታላቅ የምስጋና በዓል ነው። ሚሊዮኖች በሆራ ሀርሰዲና በሆራ ፊንፊኔ ሐይቆች በመሰብሰብ ለምለም ቄጠማ (ጮቆርሳ) እና ቢጫ አደይ አበባ ይዘው ፈጣሪን ያመሰግናሉ።',
    descOm: 'Irreechi ayyaana guddaa Oromoon waggaa waggaatti yeroo birraan bari\'u Waaqa uumaaf galata itti dhiheessudha. Hora Harsadii fi Hora Finfinneetti coqorsa laliisaa fi abaaboo keelloo qabatanii nagaa fi badhaadhinaaf kadhatu.',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1200&auto=format&fit=crop',
    tagEn: 'Thanksgiving & Renewal',
    tagAm: 'የምስጋና በዓል',
    tagOm: 'Galata & Irreeffannaa',
    highlightsEn: [
      'Holding fresh Coqorsa (wet green grass) symbolizing everlasting vitality, fertility, and peace',
      'Gathering at tranquil waters (Hora) to thank the Creator for guiding humanity across the dark rains into the golden Birraa sunshine',
      'Dressing in hand-loomed white Wandaboo adorned with vibrant red, black, and gold embroidery',
      'Communal reconciliation where grudges are forgiven before offering shared prayers',
    ],
    highlightsAm: [
      'የዘላቂ ሰላምና የሕይወት ለምለምነት መገለጫ የሆነውን ጮቆርሳ (ቄጠማ) በእጅ መያዝ',
      'ከክረምት ጭጋግ ወደ በጋው ጸሐይ ያሸጋገረንን ፈጣሪ በሐይቆች ዳርቻ ማመስገን',
      'በጥቁር፣ በቀይና በወርቃማ ጥበብ የተዋበ ነጭ ባህላዊ ወንዳቦ ልብስ መልበስ',
      'ልብን ከቂም አጽድቶ በይቅርታና በአንድነት ወደ ጸሎት መግባት',
    ],
    highlightsOm: [
      'Coqorsa laliisaa jiidhaa harkatti qabatanii mallattoo jireenyaa fi nagaatiin irreeffachu',
      'Ganna dukkanaa darbee ifti birraa waan dhufteef Waaqaaf galata dhiheessu',
      'Uffata aadaa Wandaboo bareedaa faayamee uffatanii miidhagina agarsiisu',
      'Waliif dhiifama godhanii tokkummaadhaan nagaa biyyaa fi maatiif eebba kadhachuu',
    ],
    quoteEn: '“Waaqa, you have brought us through the dark river of rain into the blooming warmth of Birraa; may our land stay peaceful and blessed.”',
    quoteAm: '“ክረምቱን አሳልፈህ ለዚህ ብሩህ የብርሃን ወር ላደረስከን ፈጣሪ ምስጋና ይሁን!”',
    quoteOm: '“Yaa Waaq, ganna nagaan nu ceesiftee birraan nu geesse; nagaa kee nuuf kenni!”',
  },
  {
    id: 'siinqee',
    category: 'philosophy',
    iconName: 'Shield',
    titleEn: 'Haadha Siinqee: The Moral Guardians',
    titleAm: 'የሲንቄ ሥርዓት፡ የሴቶች ክብርና ፍትሕ',
    titleOm: 'Sirna Siinqee fi Haadha Siinqee',
    subtitleEn: 'Sacred Authority for Peace, Justice & Women’s Rights',
    subtitleAm: 'የሴቶች ማኅበራዊ፣ መንፈሳዊና የፍትሕ ተቋም',
    subtitleOm: 'Aangoo Dubartootaa fi Nagaa Hawaasaa',
    descEn: 'The Siinqee institution represents the spiritual, social, and judicial power held exclusively by married Oromo women. Handed down from mother to daughter during marriage, the sacred Siinqee staff empowers women to halt armed conflicts, arbitrate domestic disputes, and protect the rights of women and the vulnerable with absolute moral authority.',
    descAm: 'የሲንቄ ሥርዓት የኦሮሞ ሴቶች የሞራል፣ የሰላምና የፍትሕ የበላይነት ማረጋገጫ ተቋም ነው። ሴቶች በእጃቸው የያዙትን የሲንቄ ዱላ በማንሳት ጦርነትና ጠብ እንዲቆም የማድረግ፣ የተበደሉትን የመካስ እና በረከት የመስጠት ሙሉ ክብር አላቸው።',
    descOm: 'Siinqeen ulee aadaa qulqulluu kan dubartiin gaa\'ela yeroo dhaabbattu haadha ishee irraa fudhattuudha. Aangoo nagaa buusuu, waldhabdee dhaabuu fi mirga dubartootaa eegsisuu qabdi.',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=1200&auto=format&fit=crop',
    tagEn: 'Women & Social Justice',
    tagAm: 'የሴቶች ክብር',
    tagOm: 'Mirga Dubartootaa',
    highlightsEn: [
      'The sacred Siinqee stick is a symbol of maternal dignity, justice, and spiritual mediation',
      'When mothers raise the Siinqee between combatants, fighting must cease instantly under Safuu',
      'Women gather in Ateetee rituals to pray for rain, fertility, and protection of mothers and newborns',
      'A pioneering historic model of recognized female institutional power in governance',
    ],
    highlightsAm: [
      'ሲንቄ የእናትነት ክብር፣ የሰላም አስታራቂነት እና የፍትሕ ምልክት ነው',
      'እናቶች ሲንቄያቸውን መሬት ላይ ሲጥሉ ወይም ሲያነሱ ጦርነት በአስቸኳይ መቆም አለበት',
      'በአቴቴ ሥነ-ሥርዓት ለዝናብ፣ ለምርታማነትና ለእናቶች ጤና የሚቀርብ ጸሎት',
      'በአፍሪካ ታሪክ የሴቶችን ተቋማዊ መብትና ሥልጣን ያስከበረ ጥንታዊ ሥርዓት',
    ],
    highlightsOm: [
      'Uleen Siinqee mallattoo kabaja haadhaa, haqa fi araaraati',
      'Yeroo lolli ka\'u haadhotiin Siinqee qabatanii yoo gidduu seenan lolli battalumatti dhaabbata',
      'Sirna Ateetee keessatti roobaa fi dhalataaf Waaqatti kadhannaan dhihaata',
      'Seenaa keessatti aangoo fi mirga dubartootaa ifatti kan kabachiise dhaabbata aadaati',
    ],
    quoteEn: '“When the mothers raise the Siinqee, all spears lower. Peace is the highest commandment of Safuu.”',
    quoteAm: '“እናቶች ሲንቄያቸውን ሲያነሱ ጦር ይሰበራል፤ ሰላም ይሰፍናል!”',
    quoteOm: '“Siinqeen yoo kaatu eeboon ni caba; nagaan hawaasa keessatti deebi\'a.”',
  },
  {
    id: 'music-dance',
    category: 'music',
    iconName: 'Music',
    titleEn: 'Music, Geerarsa & Regional Dances',
    titleAm: 'ሙዚቃ፣ ጌራርሳ እና ባህላዊ ጭፈራዎች',
    titleOm: 'Muziiqaa, Geerarsa fi Shubbisa Aadaa',
    subtitleEn: 'Polyphonic Melodies, Heroic Poetry & Spirited Steps',
    subtitleAm: 'የጀግንነት ቅኔ፣ ዜማ እና የደመቀ ጭፈራ',
    subtitleOm: 'Sirba Gammachuu, Geerarsa Gootummaa fi Faaruu',
    descEn: 'Oromo music and dance reflect an immense cultural landscape. From the rhythmic equestrian chants of the Shoobbiroo in Arsi and Bale to the expressive shoulder dynamics of Hararghe’s Shagoyyee, and the poetic hero-chants of Geerarsa, music is the beating pulse of festive gatherings, accompanied by Ulullee flutes, Kirara, and resounding handclapping.',
    descAm: 'የኦሮሞ ሙዚቃና ውዝዋዜ በልዩ ልዩ ክልላዊ ድምቀቶች የተሞላ ነው። የአርሲና የባሌ ሾቢሮ፣ የሐረርጌ ሻጎዬ፣ የወለጋና የሸዋ ዜማዎች እንዲሁም የጀግንነት ግጥም የሚዘረዘርበት ጌራርሳ የበዓሉን ድባብ በደስታ ያደምቃሉ።',
    descOm: 'Muziiqaa fi sirbi Oromoo naannoo naannoon amala addaa qaba. Shubbisa Shagoyyee (Harargee), Shoobbiroo (Arsii fi Baalee), Dhaanto, Karrayyuu fi Geerarsa gootummaa kan of keessatti qabudha.',
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1200&auto=format&fit=crop',
    tagEn: 'Music & Dance Traditions',
    tagAm: 'ባህላዊ ዜማና ውዝዋዜ',
    tagOm: 'Sirba fi Shubbisa',
    highlightsEn: [
      'Shagoyyee: The famous Hararghe dance emphasizing graceful neck, shoulder, and torso choreography',
      'Shoobbiroo & Hellee: Energetic pastoral dances of Arsi and Bale celebrating youth, vitality, and horsemanship',
      'Geerarsa: Dramatic spoken-word heroic poetry expressing resilience, historical triumph, and bravery',
      'Ulullee & Faaggaa: Traditional pastoral wind instruments carrying evocative melodies across highlands',
    ],
    highlightsAm: [
      'ሻጎዬ፡ አንገትና ትከሻን በሚያምር ቅላጼ የሚያንቀሳቅስ የሐረርጌ ባህላዊ ውዝዋዜ',
      'ሾቢሮ እና ሔሌ፡ በአርሲና ባሌ አካባቢ የሚደነቅ የፈረሰኞችና የወጣቶች ደማቅ ጭፈራ',
      'ጌራርሳ፡ ጀግንነትንና ታሪክን በስሜት የሚያንጎራጉር ድንቅ የቃል ቅኔ',
      'ኡሉሌና ፋጋ፡ በተራራዎች ላይ የሚያስተጋቡ ባህላዊ የዋሽንትና የትንፋሽ መሣሪያዎች',
    ],
    highlightsOm: [
      'Shagoyyee: Shubbisa miidhagaa mormaa fi kafanaatiin Harargee keessatti beekamu',
      'Shoobbiroo fi Hellee: Sirba fi shubbisa aadaa Arsii fi Baalee kan abbootii fardaa',
      'Geerarsa: Faaruu gootummaa, seenaa fi ciminna kan garaa kakaasu',
      'Ulullee fi Faaggaa: Meeshaalee aadaa afuufaman kan sagalee hawwataa qaban',
    ],
    quoteEn: '“In every beat of the handclap and verse of the Geerarsa lies the enduring memory of our ancestors.”',
    quoteAm: '“በእያንዳንዱ የከበሮ ምትና የጌራርሳ ስንኝ ውስጥ የአያቶቻችን ሕያው ታሪክ ይዘመራል!”',
    quoteOm: '“Kopheen lafa rukutee, harki wal dhahu yeroo sirbamutti gammachuun guutuu ta\'a.”',
  },
  {
    id: 'culinary-buna-qalaa',
    category: 'cuisine',
    iconName: 'UtensilsCrossed',
    titleEn: 'Buna Qalaa & Culinary Heritage',
    titleAm: 'ቡና ቃላ እና የኦሮሞ ባህላዊ ምግቦች',
    titleOm: 'Buna Qalaa fi Nyaata Aadaa Oromoo',
    subtitleEn: 'Sacred Butter-Poached Coffee & Rich Highland Dishes',
    subtitleAm: 'የተባረከው ቡና ቃላ፣ መርቃ፣ ጩኮ እና አንጮቴ',
    subtitleOm: 'Marqaa, Cukkoo, Ancootee fi Buna Qalaa Mi\'aawaa',
    descEn: 'Food in Oromo culture is deeply intertwined with hospitality, prayer, and blessing. Buna Qalaa—where whole ripe coffee cherries are gently sautéed in fragrant clarified butter (Dhadhaa)—is a holy ritual performed for ceremonies. Feasts feature golden Marqaa porridge, rich Cukkoo made from roasted barley and spiced butter, and calcium-dense Ancootee root.',
    descAm: 'የኦሮሞ የምግብ ባህል የእንግዳ ተቀባይነት፣ የፍቅርና የበረከት መገለጫ ነው። ቡና ቃላ ሙሉ የቡና ፍሬዎች በቅቤ ተቁልተው በምርቃት የሚቀርቡበት የተቀደሰ ሥርዓት ነው። ከዚህም ጋር መርቃ፣ ጣፋጭ ጩኮ፣ አንጮቴ እና ጨጨብሳ በበዓላት ገበታ ላይ በክብር ይቀርባሉ።',
    descOm: 'Buna Qalaa sirna aadaa addaa kan buna jiidhaa dhadhaa qulqulluudhaan wajjin dhiheessuudha. Marqaa dhadhaan keessatti kuufame, Cukkoo garbuu mi\'aawaa, fi Ancootee dabalatee nyaatawwan fayya-qabeessa hedduu qaba.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=1200&auto=format&fit=crop',
    tagEn: 'Gastronomy & Blessings',
    tagAm: 'ምግብና በረከት',
    tagOm: 'Nyaata & Eebba',
    highlightsEn: [
      'Buna Qalaa: Whole coffee beans cooked in spiced clarified butter, served in wooden bowls accompanied by elder prayers',
      'Marqaa: Thick roasted barley or wheat porridge cratered with clarified spiced butter and berbere',
      'Cukkoo: Roasted barley flour kneaded with abundant butter—a prized sweet delicacy that keeps fresh for months',
      'Ancootee: A nutritious indigenous tuber from Wollega prized for building bone strength and vital energy',
    ],
    highlightsAm: [
      'ቡና ቃላ፡ በቅቤ የተጠበሱ የቡና ፍሬዎች በሽማግሌዎች ተመርቀው ለበረከት የሚበሉበት',
      'መርቃ፡ በቅቤና በሚጥሚጣ ተውቦ በእንጨት ገበታ የሚቀርብ ተወዳጅ ገንፎ',
      'ጩኮ፡ ከገብስ ዱቄትና ከበርካታ ቅቤ ተቦክቶ የሚዘጋጅ ለረጅም ጊዜ የማይበላሽ ጣፋጭ ምግብ',
      'አንጮቴ፡ በወለጋ አካባቢ የሚበቅል ከፍተኛ የካልሲየም ይዘት ያለው የሥር አትክልት',
    ],
    highlightsOm: [
      'Buna Qalaa: Buna qoramee dhadhaan sa\'aa qulqulluun waadamee eebbaan dhihaatu',
      'Marqaa: Garbuu ykn qamadii irraa kan hojjetamu, dhadhaa fi daakuun kan mi\'eeffamu',
      'Cukkoo: Daakuu garbuu dhadhaa baay\'eedhaan makamee qophaa\'u, kan yeroo dheeraa turu',
      'Ancootee: Nyaata aadaa Wallaggaa kan lafee namaa cimsu fi albuuda qabu',
    ],
    quoteEn: '“May the butter of the Buna Qalaa bring softness to our speech and sweetness to our days.”',
    quoteAm: '“የቡና ቃላ ቅቤ አንደበታችንን የለሰለሰ፣ ቀናችንን የተባረከ ያድርግልን!”',
    quoteOm: '“Dhadhaan Buna Qalaa afaan keenya haa laaffisu; jireenya keenya haa mi\'eessu!”',
  },
  {
    id: 'attire-adornment',
    category: 'attire',
    iconName: 'Crown',
    titleEn: 'Attire, Jewelry & Sacred Adornments',
    titleAm: 'የባህል አልባሳት፣ ጌጣጌጥና የክብር ምልክቶች',
    titleOm: 'Uffata Aadaa, Faaya fi Mallattoolee Kabajaa',
    subtitleEn: 'Handwoven Wandaboo, Kallacha & Caaccuu Beads',
    subtitleAm: 'ወንዳቦ፣ ጫጩ፣ ሩፋ እና የክብር ጌጦች',
    subtitleOm: 'Wandaboo, Qoloo, Kallacha fi Caaccuu Faayame',
    descEn: 'Traditional Oromo clothing marries exquisite hand-loomed cotton craftsmanship with profound symbolic color palettes. White cotton garments (Wandaboo, Qoloo, Woyaa) are accented with intricate geometric borders in black (representing the unknown/Creator), red (vitality and struggle), and white (peace and wisdom)—the sacred colors of the Gadaa flag.',
    descAm: 'የኦሮሞ ባህላዊ አልባሳት በጥጥ ሽመና ጥበብና በትርጉም ባላቸው ቀለማት የተዋቡ ናቸው። ነጭ የወንዳቦና የሸማ ልብሶች በገዳ ባንዲራ ቀለማት (ጥቁር፣ ቀይና ነጭ) በጥልፍ ያሸበርቃሉ። በተጨማሪም ቃላቻ፣ ጫጩ እና ሩፋ የአመራርና የክብር ምልክት ሆነው ይደረጋሉ።',
    descOm: 'Uffanni aadaa Oromoo jirbii qulqulluu irraa harkaan dhahama. Wandaboo, Qoloo fi Woyaa irratti halluuwwan faajjii Gadaa (Gurraacha, Diimaa, Adii) miidhaginaan tolfamu. Kallacha, Caaccuu fi Ruufaan mallattoo kabajaati.',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1200&auto=format&fit=crop',
    tagEn: 'Textiles & Symbols',
    tagAm: 'አልባሳትና ጌጣጌጥ',
    tagOm: 'Uffata & Faaya',
    highlightsEn: [
      'Wandaboo & Qoloo: Pure white handwoven dresses trimmed with colorful geometric stitchery along the hems',
      'Kallacha: A sacred cast-metal forehead insignia worn by high Gadaa leaders and Abbaa Malkaa during rituals',
      'Caaccuu: Elaborate beaded leather ornaments worn proudly by Haadha Siinqee elders symbolizing fertility and peace',
      'Ruufa: The ceremonial turban cloth embodying the tripartite colors of cosmic balance (Black, Red, White)',
    ],
    highlightsAm: [
      'ወንዳቦ እና ቆሎ፡ በድንበሩ ላይ በልዩ ቀለም የተጠለፈ ነጭ የጥጥ ቀሚስ',
      'ቃላቻ፡ በአባ ገዳዎችና በባህል መሪዎች ግንባር ላይ የሚታሰር የተቀደሰ የክብር ምልክት',
      'ጫጩ፡ በሴት አባቶችና በሲንቄ እናቶች የሚደረግ በዕንቁና በቆዳ የተሠራ ጌጥ',
      'ሩፋ፡ የገዳን ሦስት ቀለማት (ጥቁር፣ ቀይ፣ ነጭ) የያዘ የክብር የራስ ጥምጥም',
    ],
    highlightsOm: [
      'Wandaboo fi Qoloo: Jirbii harkaan fooyame irraa kan tolfamu, mudhii fi qonyee irratti kan faayamu',
      'Kallacha: Adda irratti kan hidhatamu, mallattoo aadaa fi qulqullummaa Abbootii Gadaati',
      'Caaccuu: Faaya callee fi gogaa irraa tolfame kan Haadhotiin Siinqee mudhii fi harkatti godhatan',
      'Ruufa: Faaya mataa kan halluuwwan Gadaa sadiin (Gurraacha, Diimaa, Adii) bareedu',
    ],
    quoteEn: '“Each thread woven into our cloth carries the colors of our land, our history, and our enduring peace.”',
    quoteAm: '“በልብሶቻችን ላይ የተጠለፈው እያንዳንዱ ፈትል የሀገራችንን ውበትና የሰላማችንን ታሪክ ይናገራል!”',
    quoteOm: '“Faayayni uffata aadaa keenyaa mallattoo eenyummaa fi kabaja dhalootaati.”',
  },
];

export const OROMIA_GALLERY_PHOTOS: OromiaGalleryPhoto[] = [
  {
    id: 'og-1',
    titleEn: 'Irreecha Gathering at Hora Harsadi',
    titleAm: 'የኢሬቻ በዓል በሆራ ሀርሰዲ ሐይቅ',
    titleOm: 'Ayyaana Irreechaa Hora Harsadii',
    captionEn: 'Millions dressed in radiant Wandaboo garments holding fresh Coqorsa grass at dawn beside the sacred lake in Bishoftu.',
    captionAm: 'ሚሊዮኖች ነጭ ወንዳቦ ለብሰው ለምለም ቄጠማ ይዘው በቢሾፍቱ ሆራ ሀርሰዲ ሐይቅ ዳርቻ ፈጣሪን ሲያመሰግኑ።',
    captionOm: 'Miliyoononni uffata aadaa Wandaboo uffatanii coqorsa harkatti qabatanii Hora Harsadiitti Waaqa galateeffatan.',
    category: 'irreecha',
    locationEn: 'Hora Harsadi, Bishoftu',
    locationAm: 'ሆራ ሀርሰዲ፣ ቢሾፍቱ',
    locationOm: 'Hora Harsadii, Bishooftuu',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'tall',
  },
  {
    id: 'og-2',
    titleEn: 'Bale Mountains Alpine Plateau & Wild Valleys',
    titleAm: 'የባሌ ተራሮች ሳኔቲ ፕላቶ እና የአፍሮ-አልፓይን ውበት',
    titleOm: 'Gaarreen Baalee fi Dirree Saanettii',
    captionEn: 'Africa’s largest Afro-alpine ecosystem where giant Lobelias flourish under towering misty peaks reaching 4,377 meters.',
    captionAm: 'በአፍሪካ ትልቁ የአፍሮ-አልፓይን ምድር፣ ግዙፍ የሎቤሊያ እፅዋትና የተንጣለሉ ሰንሰለታማ ተራሮች።',
    captionOm: 'Lafoo alpinee addunyaa irratti beekamaa fi tulluuwwan dhaabbatan kan Gaara Baalee.',
    category: 'nature',
    locationEn: 'Bale Mountains National Park',
    locationAm: 'የባሌ ተራሮች ብሔራዊ ፓርክ',
    locationOm: 'Paarkii Biyyooleessaa Gaarreen Baalee',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'wide',
  },
  {
    id: 'og-3',
    titleEn: 'Wenchi Volcanic Crater Lake',
    titleAm: 'የወንጪ እሳተ-ገሞራ ፍልፍል ሐይቅ',
    titleOm: 'Haroo Wancii Hawwataa',
    captionEn: 'A breathtaking emerald crater lake framed by dramatic caldera walls, waterfalls, mineral hot springs, and ancient forests.',
    captionAm: 'አረንጓዴ ተፈጥሮ፣ ፏፏቴዎችና ፍልውሃዎች የተከበበው አስደናቂው የወንጪ እሳተ ገሞራ ሐይቅ።',
    captionOm: 'Haroo caldera qulqulluu fi bosona laliisaan kan marfame, Haroo Wancii Amboo biratti.',
    category: 'nature',
    locationEn: 'Wenchi, West Shewa',
    locationAm: 'ወንጪ፣ ምዕራብ ሸዋ',
    locationOm: 'Wancii, Shawaa Lixaa',
    image: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'tall',
  },
  {
    id: 'og-4',
    titleEn: 'The Sacred Sycamore Odaa Tree',
    titleAm: 'የተከበረው ጥንታዊው የኦዳ ዛፍ',
    titleOm: 'Muka Odaa Qulqulluu Gadaa',
    captionEn: 'The revered sycamore fig tree serving as the legislative meeting shade for Chaffe assemblies throughout Oromo history.',
    captionAm: 'የገዳ ሕጎች የሚወጡበትና የዴሞክራሲ ውሳኔዎች የሚተላለፉበት የተቀደሰው ታሪካዊ የኦዳ ዛፍ።',
    captionOm: 'Muka guddaa aadaa kan seera Gadaa itti tumamu fi nagaan itti bu\'u.',
    category: 'heritage',
    locationEn: 'Odaa Nabee, Central Oromia',
    locationAm: 'ኦዳ ነቤ፣ ማዕከላዊ ኦሮሚያ',
    locationOm: 'Odaa Nabee, Oromiyaa Gidduugaleessaa',
    image: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'square',
  },
  {
    id: 'og-5',
    titleEn: 'Ceremonial Buna Qalaa in Wooden Bowl',
    titleAm: 'በእንጨት ገበታ የቀረበ የተባረከ ቡና ቃላ',
    titleOm: 'Sirna Buna Qalaa Dhadhaan Mi\'eeffame',
    captionEn: 'Plump whole coffee cherries sautéed gently in golden clarified spiced butter, prepared for prayer and elder blessings.',
    captionAm: 'በቅቤ ተቁልቶ በእንጨት ገበታ ለምርቃትና ለእንግዳ ክብር የሚቀርብ ልዩ ባህላዊ ቡና ቃላ።',
    captionOm: 'Buna lalisaa dhadhaa qulqulluun waadamee eebbaaf kan dhihaatu.',
    category: 'culinary',
    locationEn: 'Jimma Coffee Highlands',
    locationAm: 'ጅማ የቡና ምድር',
    locationOm: 'Baddaa Bunaa Jimmaa',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'tall',
  },
  {
    id: 'og-6',
    titleEn: 'Traditional Hand-Embroidered Wandaboo Dress',
    titleAm: 'በጥበብ የተዋበ ነጭ የወንዳቦ ልብስ',
    titleOm: 'Uffata Wandaboo Faayamee Tolfame',
    captionEn: 'Fine hand-spun cotton woven with bold red, black, and gold geometric cross-stitch along collar and hems.',
    captionAm: 'በጥቁር፣ ቀይና ወርቃማ ጥበብ የተጠለፈ ነጭ የጥጥ ወንዳቦ ቀሚስ።',
    captionOm: 'Uffata aadaa shamarranii jirbii irraa harkaan tolfame kan bareedina qabu.',
    category: 'attire',
    locationEn: 'Cultural Weaving Studio',
    locationAm: 'የባህል ሽመና ማዕከል',
    locationOm: 'Iddoo Hojii Aadaa',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'wide',
  },
  {
    id: 'og-7',
    titleEn: 'Haadha Siinqee Bearing the Sacred Staff',
    titleAm: 'የሲንቄ እናቶች በክብር ሲያልፉ',
    titleOm: 'Haadha Siinqee Ulee Qulqulluu Qabatanii',
    captionEn: 'Revered women elders holding hand-carved Siinqee sticks and wearing Caaccuu bead necklaces during peace ceremonies.',
    captionAm: 'የተከበሩ እናቶች የሰላም፣ የፍትሕና የእርቅ ምልክት የሆነውን ሲንቄ ይዘው በበዓል ሲጓዙ።',
    captionOm: 'Haadhotiin Siinqee ulee aadaa qabatanii nagaa fi araaraaf yeroo deeman.',
    category: 'heritage',
    locationEn: 'Arsi Highlands',
    locationAm: 'የአርሲ ደጋማ ስፍራዎች',
    locationOm: 'Baddaa Arsii',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'square',
  },
  {
    id: 'og-8',
    titleEn: 'Traditional Marqaa Feast with Spiced Butter',
    titleAm: 'በቅቤና በሚጥሚጣ የተዘጋጀ ባህላዊ መርቃ',
    titleOm: 'Nyaata Marqaa Dhadhaa Sa\'aan Mi\'aawe',
    captionEn: 'Rich roasted barley porridge cratered with aromatic spiced clarified butter, served in authentic hand-carved wood bowls.',
    captionAm: 'የተልባና የገብስ ገንፎ በማዕከሉ በሚገኝ ጥርት ያለ ቅቤ ታጅቦ ለእንግዳ ሲቀርብ።',
    captionOm: 'Marqaa aadaa mi\'aawaa dhadhaa baay\'ee qabu kan ayyaanaaf qophaa\'u.',
    category: 'culinary',
    locationEn: 'Traditional Kitchen, Shewa',
    locationAm: 'የባህል ማዕድ፣ ሸዋ',
    locationOm: 'Kukina Aadaa, Shawaa',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'tall',
  },
  {
    id: 'og-9',
    titleEn: 'Hora Finfinnee Irreecha Thanksgiving',
    titleAm: 'የኢሬቻ በዓል በሆራ ፊንፊኔ ማዕከል',
    titleOm: 'Irreecha Malkaa Hora Finfinnee',
    captionEn: 'A joyful sea of white attire and fresh green grass celebrants blessing the historic water spring in central Finfinnee.',
    captionAm: 'በፊንፊኔ እምብርት በሚገኘው የሆራ መልካ ለምለም ቄጠማ ይዘው ፈጣሪን የሚያመሰግኑ የበዓሉ ታዳሚዎች።',
    captionOm: 'Gammachuu guddaa ummanni uffata adii uffatee Hora Finfinneetti Waaqeffatu.',
    category: 'irreecha',
    locationEn: 'Finfinnee (Addis Ababa)',
    locationAm: 'ፊንፊኔ (አዲስ አበባ)',
    locationOm: 'Finfinnee',
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'wide',
  },
  {
    id: 'og-10',
    titleEn: 'Arsi & Bale Traditional Horsemen',
    titleAm: 'የአርሲና የባሌ ፈረሰኞች ግርማ',
    titleOm: 'Abbootii Fardaa Arsii fi Baalee',
    captionEn: 'Master riders adorned in ceremonial cloaks galloping in formation across wide highland meadows for cultural exhibitions.',
    captionAm: 'የባህል ካባ የለበሱ የአርሲና ባሌ ፈረሰኞች በሜዳው ላይ የፈረስ ጉግስ ትርዒት ሲያሳዩ።',
    captionOm: 'Abbootii fardaa aadaa kan farda isaanii miidhagsanii gootummaan shubbisan.',
    category: 'heritage',
    locationEn: 'Dodola Meadows, West Arsi',
    locationAm: 'ዶዶላ ሜዳ፣ ምዕራብ አርሲ',
    locationOm: 'Dirree Doodolaa, Arsii Lixaa',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'tall',
  },
  {
    id: 'og-11',
    titleEn: 'Lush Coffee Forests of Kaffa & Jimma',
    titleAm: 'የጅማና የከፋ አረንጓዴ የቡና ደኖች',
    titleOm: 'Bosona Bunaa Jimmaa fi Kaffaa',
    captionEn: 'The wild cradle of Coffea Arabica where ancient heirloom trees thrive beneath towering indigenous canopy trees.',
    captionAm: 'የዓረቢካ ቡና መገኛ የሆኑት ጥንታዊና ለምለም የቡና ዛፎች በጅማና በከፋ ደኖች መካከል።',
    captionOm: 'Bosona uumamaa buna Arabikaa kan addunyaa guutuuf madda ta\'e.',
    category: 'nature',
    locationEn: 'Jimma Biosphere Reserve',
    locationAm: 'የጅማ ባዮስፌር ሪዘርቭ',
    locationOm: 'Bosona Uumamaa Jimmaa',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'wide',
  },
  {
    id: 'og-12',
    titleEn: 'Shagoyyee & Youth Cultural Dancers',
    titleAm: 'የሻጎዬ ወጣት ባህላዊ ደናሾች',
    titleOm: 'Dargaggoota Shubbisa Shagoyyee',
    captionEn: 'Vibrant youth wearing beaded headbands and flowing attire executing the high-energy movements of Hararghe tradition.',
    captionAm: 'በዕንቁ የተዋበ የራስ ጌጥ አድርገው ደማቁን የሻጎዬ ውዝዋዜ የሚያሳዩ ወጣቶች።',
    captionOm: 'Shamarran fi dargaggoota aadaa Harargee calleen faayamanii shubbisan.',
    category: 'attire',
    locationEn: 'Hararghe Cultural Center',
    locationAm: 'የሐረርጌ ባህል ማዕከል',
    locationOm: 'Wiirtuu Aadaa Harargee',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1200&auto=format&fit=crop',
    aspectRatio: 'square',
  },
];
